name: Generate Docs PDF
on:
  push:
    branches:
      - main
  workflow_dispatch:    
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps: 
    - name: Install Prince
      run: |
        curl https://www.princexml.com/download/prince-15.4.1-linux-generic-x86_64.tar.gz -O
        tar zxf prince-15.4.1-linux-generic-x86_64.tar.gz
        cd prince-15.4.1-linux-generic-x86_64
        yes "" | sudo ./install.sh
    - name: Build PDF
      run: npx docusaurus-prince-pdf -u https://docs.projectbluefin.io
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: result
        # The output filename can be specified with --output option
        path: pdf/bluefin.pdf
        if-no-files-found: error
