name: check-spelling

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.fedora_version }}
  cancel-in-progress: true

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for typos
        uses: crate-ci/typos@75e5143dfa95d6a94768588f7b971904f68b8ddd # version 1.0.4
        with:
          files: ./README.md ./docs ./pages
